[package]
name = "url_shortener"
version = "0.1.0"
authors = ["Zachary E Sohovich <zacharyesohovich@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
now_lambda = "0.1"
